# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  sr_ee_joint1:
    has_velocity_limits: true
    max_velocity: 2.1749999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  sr_ee_joint10:
    has_velocity_limits: true
    max_velocity: 2.1749999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  sr_ee_joint11:
    has_velocity_limits: true
    max_velocity: 2.1749999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  sr_ee_joint12:
    has_velocity_limits: true
    max_velocity: 2.1749999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  sr_ee_joint13:
    has_velocity_limits: true
    max_velocity: 2.1749999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  sr_ee_joint14:
    has_velocity_limits: true
    max_velocity: 2.1749999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  sr_ee_joint2:
    has_velocity_limits: true
    max_velocity: 2.1749999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  sr_ee_joint3:
    has_velocity_limits: true
    max_velocity: 2.1749999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  sr_ee_joint4:
    has_velocity_limits: true
    max_velocity: 2.1749999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  sr_ee_joint5:
    has_velocity_limits: true
    max_velocity: 2.1749999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  sr_ee_joint6:
    has_velocity_limits: true
    max_velocity: 2.1749999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  sr_ee_joint7:
    has_velocity_limits: true
    max_velocity: 2.1749999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  sr_ee_joint8:
    has_velocity_limits: true
    max_velocity: 2.1749999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  sr_ee_joint9:
    has_velocity_limits: true
    max_velocity: 2.1749999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  sr_joint1:
    has_velocity_limits: true
    max_velocity: 2.1749999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  sr_joint2:
    has_velocity_limits: true
    max_velocity: 2.1749999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  sr_joint3:
    has_velocity_limits: true
    max_velocity: 2.1749999999999998
    has_acceleration_limits: false
    max_acceleration: 0