<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <xacro:property name="offset" value="0.1" />
    <xacro:property name="l0_radius" value="0.6" />
    <xacro:property name="l0_length" value="0.2" />
    <xacro:property name="l1_radius" value="0.4" />
    <xacro:property name="l1_length" value="0.3" />
    <xacro:property name="l2_radius" value="0.08" />
    <xacro:property name="l2_length" value="0.8" />

    <xacro:macro name="link_inertia" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="1e-3" ixy="0.0" ixz="0.0"
                     iyy="1e-3" iyz="0.0"
                     izz="1e-3" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="link_visual" params="radius length xyz rpy">  <!-- only for cylinder -->
        <visual>
            <geometry>
                <cylinder radius="${radius}" length="${length}"/>
            </geometry>
            <material name="blue"/>
            <origin xyz="${xyz}" rpy="${rpy}"/>
        </visual>
    </xacro:macro>

    <xacro:macro name="link_collision" params="radius length">  <!-- only for cylinder -->
        <collision>
            <geometry>
                <cylinder radius="${radius}" length="${length}"/>
            </geometry>
        </collision>
    </xacro:macro>

    <xacro:macro name="sr_link_module" params="radius length xyz rpy mass">  <!-- only for cylinder -->
        <xacro:link_visual radius="${radius}" length="${length}" xyz="0 0 ${length/2}" rpy="0 0 0"/>
        <xacro:link_collision radius="${radius}" length="${length}"/>
        <xacro:link_inertia mass="${mass}"/>
    </xacro:macro>

    <xacro:macro name="sr_joint" params="rpy xyz parent child axis">  <!-- only for revolute -->
        <origin rpy="${rpy}" xyz="${xyz}"/>
        <parent link="${parent}"/>
        <child link="${child}"/>
        <axis xyz="${axis}" />
        <limit effort="87" lower="-0.785" upper="0.785" velocity="2.1750"/>
        <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-2.8973" soft_upper_limit="2.8973"/>
    </xacro:macro>


</robot>